
package com.rohit.webservice.employee;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeeImpService", targetNamespace = "http://employee.webservice.rohit.com/", wsdlLocation = "http://localhost:9999/ws/employee?wsdl")
public class EmployeeImpService
    extends Service
{

    private final static URL EMPLOYEEIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEEIMPSERVICE_EXCEPTION;
    private final static QName EMPLOYEEIMPSERVICE_QNAME = new QName("http://employee.webservice.rohit.com/", "EmployeeImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/employee?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEEIMPSERVICE_WSDL_LOCATION = url;
        EMPLOYEEIMPSERVICE_EXCEPTION = e;
    }

    public EmployeeImpService() {
        super(__getWsdlLocation(), EMPLOYEEIMPSERVICE_QNAME);
    }

    public EmployeeImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEEIMPSERVICE_QNAME, features);
    }

    public EmployeeImpService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEEIMPSERVICE_QNAME);
    }

    public EmployeeImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEEIMPSERVICE_QNAME, features);
    }

    public EmployeeImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeeInterface
     */
    @WebEndpoint(name = "EmployeeImpPort")
    public EmployeeInterface getEmployeeImpPort() {
        return super.getPort(new QName("http://employee.webservice.rohit.com/", "EmployeeImpPort"), EmployeeInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeInterface
     */
    @WebEndpoint(name = "EmployeeImpPort")
    public EmployeeInterface getEmployeeImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://employee.webservice.rohit.com/", "EmployeeImpPort"), EmployeeInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEEIMPSERVICE_EXCEPTION!= null) {
            throw EMPLOYEEIMPSERVICE_EXCEPTION;
        }
        return EMPLOYEEIMPSERVICE_WSDL_LOCATION;
    }

}
