
package com.rohit.webservice.salary;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SalaryInterface", targetNamespace = "http://salary.webservice.rohit.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SalaryInterface {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "salary", targetNamespace = "http://salary.webservice.rohit.com/", className = "com.rohit.webservice.salary.Salary")
    @ResponseWrapper(localName = "salaryResponse", targetNamespace = "http://salary.webservice.rohit.com/", className = "com.rohit.webservice.salary.SalaryResponse")
    @Action(input = "http://salary.webservice.rohit.com/SalaryInterface/salaryRequest", output = "http://salary.webservice.rohit.com/SalaryInterface/salaryResponse")
    public boolean salary(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTotalSalary", targetNamespace = "http://salary.webservice.rohit.com/", className = "com.rohit.webservice.salary.GetTotalSalary")
    @ResponseWrapper(localName = "getTotalSalaryResponse", targetNamespace = "http://salary.webservice.rohit.com/", className = "com.rohit.webservice.salary.GetTotalSalaryResponse")
    @Action(input = "http://salary.webservice.rohit.com/SalaryInterface/getTotalSalaryRequest", output = "http://salary.webservice.rohit.com/SalaryInterface/getTotalSalaryResponse")
    public Long getTotalSalary(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
