
package com.rohit.webservice.salary;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SalaryImpService", targetNamespace = "http://salary.webservice.rohit.com/", wsdlLocation = "http://localhost:9999/ws/salary?wsdl")
public class SalaryImpService
    extends Service
{

    private final static URL SALARYIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException SALARYIMPSERVICE_EXCEPTION;
    private final static QName SALARYIMPSERVICE_QNAME = new QName("http://salary.webservice.rohit.com/", "SalaryImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/salary?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SALARYIMPSERVICE_WSDL_LOCATION = url;
        SALARYIMPSERVICE_EXCEPTION = e;
    }

    public SalaryImpService() {
        super(__getWsdlLocation(), SALARYIMPSERVICE_QNAME);
    }

    public SalaryImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SALARYIMPSERVICE_QNAME, features);
    }

    public SalaryImpService(URL wsdlLocation) {
        super(wsdlLocation, SALARYIMPSERVICE_QNAME);
    }

    public SalaryImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SALARYIMPSERVICE_QNAME, features);
    }

    public SalaryImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SalaryImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SalaryInterface
     */
    @WebEndpoint(name = "SalaryImpPort")
    public SalaryInterface getSalaryImpPort() {
        return super.getPort(new QName("http://salary.webservice.rohit.com/", "SalaryImpPort"), SalaryInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SalaryInterface
     */
    @WebEndpoint(name = "SalaryImpPort")
    public SalaryInterface getSalaryImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://salary.webservice.rohit.com/", "SalaryImpPort"), SalaryInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SALARYIMPSERVICE_EXCEPTION!= null) {
            throw SALARYIMPSERVICE_EXCEPTION;
        }
        return SALARYIMPSERVICE_WSDL_LOCATION;
    }

}
